BigDataFrontEnd/BigDataFrontEnd/BigDataFrontEnd/urls.py
"""
Definition of urls for BigDataFrontEnd.
"""

from datetime import datetime
from django.conf.urls import patterns, url
from app.forms import BootstrapAuthenticationForm
from django.contrib.auth import views as auth_views
from signup.views import signup, login

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'app.views.home', name='home'),    
    url(r'^contact$', 'app.views.contact', name='contact'),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),

    #signup
    url(r'^accounts/login/$', 
        auth_views.login, 
        {'template_name': 'signup/login.html'}),
    url(r'^account/$', 'signup.views.mylogin', name='login'),
    url(r'^account/signup/$', 'signup.views.signup', name='signup'),
    url(r'^account/signup/success/$', 'signup.views.register_success', name='registerSuccess'),
    url(r'^account/passwordrecovery/$', 'signup.views.password_recover', name='passwordrecovery'),
    url(r'^account/passwordrecovery/emailsent/$', 'signup.views.password_recover_email_sent', name='password_recover_email_sent'),
    url(r'^account/passwordrecovery/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            'signup.views.reset_confirm', name='reset_confirm'),
    url(r'^provider/profile/$', 'providerprofile.views.provider_profile', name='providerprofile'),
    url(r'^provider/dashboard/$', 'providerprofile.views.provider_dashboard', name='providerdashboard')


    #userprofile



    #clientprofile






    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

BigDataFrontEnd/BigDataFrontEnd/providerprofile/models.py
from django.db import models
from django.contrib.auth.models import User

# providerprofile app

# providerprofile tables under user.models

BigDataFrontEnd/BigDataFrontEnd/user/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.auth.models import User

# user app
class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Other fields here
    email2 = models.EmailField(blank=True, null=True)
    isProvider = models.BooleanField(default=False)
    isClient = models.BooleanField(default=False)

class UserProfileTr(models.Model): 
    userProfile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    languageCode = models.CharField(max_length=2)
    bioC = models.CharField(max_length=400, blank=True, null=True)
    bioP = models.CharField(max_length=400, blank=True, null=True)

class RateAgg(models.Model):
    # This field is required.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Other fields here
    ProviderRateAgg = models.DecimalField(max_digits=3, decimal_places=2)
    ClientRateAgg = models.DecimalField(max_digits=3, decimal_places=2)


# -------- clientprofile tables (placed in user.models due to circular dependencies, can't compile otherwise) --------

class Organization(models.Model):
    memberCnt = models.IntegerField(default=1)

class OrganizationTr(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    languageCode = models.CharField(max_length=2)
    name = models.CharField(max_length=50)
    companyStmt = models.CharField(max_length=400, blank=True, null=True)

class Client(models.Model):
    # This field is required.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Other fields here
    organization = models.ForeignKey(Organization, blank=True, null=True)

# -------- end clientprofile tables --------

# -------- providerprofile tables (placed in user.models due to circular dependencies, can't compile otherwise) --------
class Provider(models.Model):
    # This field is required.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class SkillDef(models.Model):
    pass

class SkillDefTr(models.Model):
    skillDef = models.ForeignKey(SkillDef, on_delete=models.CASCADE)

    languageCode = models.CharField(max_length=2)
    skillName = models.CharField(max_length=50)

class Skill(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, default=0)
    skillDef = models.ForeignKey(SkillDef, on_delete=models.CASCADE, default=0)
    skillNum = models.IntegerField(default=1)

#temp table. Create new standard skill name for Skill table.
class UndefinedSkill(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, default=0)

    languageCode = models.CharField(max_length=2)
    undefinedSkill = models.CharField(max_length=50)

# -------- end providerprofile --------

class CategoryDef(models.Model):
    pass

class CategoryDefTr(models.Model):
    categoryDef = models.ForeignKey(CategoryDef, on_delete=models.CASCADE)

    languageCode = models.CharField(max_length=2)
    categoryName = models.CharField(max_length=50)

class CategoryProvider(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    categoryDef = models.ForeignKey(CategoryDef, on_delete=models.CASCADE)
    categoryNum = models.IntegerField(default=1)

class CategoryClient(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    categoryDef = models.ForeignKey(CategoryDef, on_delete=models.CASCADE)
    categoryNum = models.IntegerField(default=1)

class Title(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, blank=True, null=True)

class TitleTr(models.Model):
    title = models.ForeignKey(Title, on_delete=models.CASCADE)

    languageCode = models.CharField(max_length=2)
    titleName = models.CharField(max_length=50, blank=True, null=True)

class LanguageDef(models.Model):
    pass

class LanguageDefTr(models.Model):
    languageDef = models.ForeignKey(LanguageDef, on_delete=models.CASCADE)

    languageCode = models.CharField(max_length=2)
    languageName = models.CharField(max_length=50) 

class Language(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    languageDef = models.ForeignKey(LanguageDef, on_delete=models.CASCADE, default=0)
    languageNum = models.IntegerField(default=1)

#no translation table is needed since client-provider will communicate via one language
class Feedback(models.Model):
    # The reviewer
    user = models.ForeignKey(User)

    # Other fields here
    client = models.ForeignKey(Client, blank=True, null=True)
    provider = models.ForeignKey(Provider, blank=True, null=True)
    languageCode = models.CharField(max_length=2)
    feedback = models.CharField(max_length=400, blank=True, null=True)
    rate = models.IntegerField()

def assure_user_profile_exists(pk):
    
    #Creates a user profile if a User exists, but the
    #profile does not exist.  Use this in views or other
    #places where you don't have the user object but have the pk.
    
    user = User.objects.get(pk=pk)
    try:
        # fails if it doesn't exist
        userprofile = user.userprofile
    except UserProfile.DoesNotExist:
        userprofile = UserProfile(user=user)
        userprofile.save()
    return


def create_user_profile(**kwargs):
    UserProfile.objects.get_or_create(user=kwargs['user'])

BigDataFrontEnd/BigDataFrontEnd/providerprofile/views.py
from providerprofile.forms import ProviderEditForm
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from user.models import *
from location.models import *
from django.core.urlresolvers import reverse


def provider_profile(request):

    if (request.method == 'POST') and ('providerProfileUpdate' in request.POST):

        postExtractedUsername = request.POST['username']

        # Get the user object based on the extracted username
        userObj = get_object_or_404(User, username=postExtractedUsername) 
        providerObj, created = Provider.objects.get_or_create(user=userObj)  
  
        # Title
        titleObj, created = Title.objects.get_or_create(provider=providerObj)
        titleTrObj, created = TitleTr.objects.update_or_create(title=titleObj, defaults={'titleName': request.POST['title']}, languageCode='en')

        # Summary
        userProf, created = UserProfile.objects.get_or_create(user=userObj)
        userProfTr, created = UserProfileTr.objects.update_or_create(userProfile=userProf, defaults={'bioP': request.POST['summary']})

        # Skillset
        skillsetsStr = request.POST['skillsets']
        

        if(skillsetsStr != ''):
            #remove extra space and delete spaces that may be misrecognized as a valid skill
            skillsetsList = set(''.join(skillsetsStr.split(',')).split())
            curSkillsetCnt = Skill.objects.filter(provider=providerObj).count()
            skillsetsLen = len(skillsetsList)
            skillNum = 1
            #if current skillsets count is greater than passed-in skillsets count, delete 
            #all skills of user above passed-in skillsets count
            if(skillsetsLen < curSkillsetCnt):
                Skill.objects.filter(provider=providerObj, skillNum__gt = skillsetsLen).delete()
            
            for skillset in skillsetsList:
                try:
                    #Find if existing skillset exists in definition table
                    skillDefTrObj = SkillDefTr.objects.get(languageCode = 'en', skillName = skillset.strip())
                except SkillDefTr.DoesNotExist:
                    #Create new skillset definition if it doesn't exist
                    skillDefObj = SkillDef.objects.create()
                    skillDefTrObj = SkillDefTr.objects.create(skillDef = skillDefObj, languageCode='en', skillName = skillset.strip())
                    skillDefTrObj.save()

                skillObj, created = Skill.objects.update_or_create(provider = providerObj, defaults={'skillDef': skillDefTrObj.skillDef}, skillNum = skillNum)
                skillNum += 1
        #if skillset list is empty, delete all skills related to provider
        else:
            Skill.objects.filter(provider=providerObj).delete()
        
        # Country
        countryDefTrObj = CountryDefTr.objects.get(id=request.POST['country'], languageCode='en')
        locObj, created = Location.objects.update_or_create(user=userObj, defaults={'countryDef': countryDefTrObj.countryDef})

        # Language 1
        langDefTrObj1 = LanguageDefTr.objects.get(id=request.POST['language1'], languageCode='en')
        langObj1, created = Language.objects.update_or_create(user=userObj, defaults={'languageDef': langDefTrObj1.languageDef}, languageNum=1)      

        # Language 2
        langDefTrObj2 = LanguageDefTr.objects.get(id=request.POST['language2'], languageCode='en')
        langObj2, created = Language.objects.update_or_create(user=userObj, defaults={'languageDef': langDefTrObj2.languageDef}, languageNum=2)
        
        # Language 3
        langDefTrObj3 = LanguageDefTr.objects.get(id=request.POST['language3'], languageCode='en')
        langObj3, created = Language.objects.update_or_create(user=userObj, defaults={'languageDef': langDefTrObj3.languageDef}, languageNum=3)

        # Categories 1
        catDefTrObj1 = CategoryDefTr.objects.get(id=request.POST['categories1'], languageCode='en')
        catObj1, created = CategoryProvider.objects.update_or_create(provider=providerObj, defaults={'categoryDef': catDefTrObj1.categoryDef}, categoryNum = 1)

        # Categories 2
        catDefTrObj2 = CategoryDefTr.objects.get(id=request.POST['categories2'], languageCode='en')
        catObj2, created = CategoryProvider.objects.update_or_create(provider=providerObj, defaults={'categoryDef': catDefTrObj2.categoryDef}, categoryNum = 2)

        # Categories 3
        catDefTrObj3 = CategoryDefTr.objects.get(id=request.POST['categories3'], languageCode='en')
        catObj3, created = CategoryProvider.objects.update_or_create(provider=providerObj, defaults={'categoryDef': catDefTrObj3.categoryDef}, categoryNum = 3)

       # Doesn't recognize whether or not user is logged in because 'request'
       # is not passed on to this page...use render
       # return HttpResponseRedirect('/account/signup/success') # render(request, reverse('registerSuccess'))
        return redirect('/')
    else:
        form = ProviderEditForm(request.user)
        return render(request, 'providerprofile/providerprofile.html', {'form': form})   

def provider_dashboard(request):

     return render(request, 'providerdashboard/pdashboard.html')



    
          
    

BigDataFrontEnd/BigDataFrontEnd/providerprofile/templates/providerprofile/providerprofile.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
{% if user.is_authenticated %}
<style>
    .form-group {
    width: 100%;
}
    #id_title {
        width: 250px;
    }
</style>
<div class="row">
<div class="col-md-3"></div>     
<div class="col-md-6">
       <h2>Provider Profile</h2>
     <div id="my_popup">
        <img style="width: 125px; height: 125px;" src="{% static "ajax_loader_blue_512.gif" %}" />
    </div>
        <form onsubmit="myFunction()" action="" method="post">
            {% if form.non_field_errors %}                      
            <div style="color:#b94a48">
                {{form.non_field_errors}}
            </div>
            {% endif %}         
         {% csrf_token %} 
         {% for field in form %}
            <fieldset class="form-group" id="{{field.name}}">
                {% if field.name == 'language1' %}
                    <label class="control-label" for="id_{{ field.name }}">Language 1:</label>
                {% elif field.name == 'language2' %}
                    <label class="control-label" for="id_{{ field.name }}">Language 2:</label>
                {% elif field.name == 'language3' %}
                    <label class="control-label" for="id_{{ field.name }}">Language 3:</label>
                {% elif field.name == 'categories1' %}
                    <label class="control-label" for="id_{{ field.name }}">Category 1:</label>
                 {% elif field.name == 'categories2' %}
                    <label class="control-label" for="id_{{ field.name }}">Category 2:</label>
                {% elif field.name == 'categories3' %}
                    <label class="control-label" for="id_{{ field.name }}">Category 3:</label>
                {% else %}
                    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}:</label>
                {% endif %}          
                {% if field.name == 'title' %}        
                    <input type="text" class="form-control" name="{{ field.name }}" id="id_{{ field.name }}" value="{{ form.fields.title.initial }}"> 
                {% endif %}      
                {% if field.name == 'country' %}        
                    <select id="id_{{field.name}}" name="{{ field.name }}">
                        {% for id, name in form.fields.country.choices %}
                            <option value="{{ id }}">{{ name }}</option>                            
                        {% endfor %}                   
                    </select>
                {% endif %}
                {% if field.name == 'language1' %}        
                    <select id="id_{{field.name}}" name="{{ field.name }}">
                        {% for id, name in form.fields.language1.choices %}
                            <option value="{{ id }}">{{ name }}</option>                            
                        {% endfor %}                   
                    </select>
                {% endif %} 
                {% if field.name == 'language2' %}        
                    <select id="id_{{field.name}}" name="{{ field.name }}">
                        {% for id, name in form.fields.language2.choices %}
                            <option value="{{ id }}">{{ name }}</option>                            
                        {% endfor %}                   
                    </select>
                {% endif %}
                {% if field.name == 'language3' %}        
                    <select id="id_{{field.name}}" name="{{ field.name }}">
                        {% for id, name in form.fields.language3.choices %}
                            <option value="{{ id }}">{{ name }}</option>                            
                        {% endfor %}                   
                    </select>
                {% endif %}  
                  {% if field.name == 'categories1' %}        
                    <select id="id_{{field.name}}" name="{{ field.name }}">
                        {% for id, name in form.fields.categories1.choices %}
                            <option value="{{ id }}">{{ name }}</option>                            
                        {% endfor %}                   
                    </select>
                {% endif %}
                  {% if field.name == 'categories2' %}        
                    <select id="id_{{field.name}}" name="{{ field.name }}">
                        {% for id, name in form.fields.categories2.choices %}
                            <option value="{{ id }}">{{ name }}</option>                            
                        {% endfor %}                   
                    </select>
                {% endif %}
                  {% if field.name == 'categories3' %}        
                    <select id="id_{{field.name}}" name="{{ field.name }}">
                        {% for id, name in form.fields.categories3.choices %}
                            <option value="{{ id }}">{{ name }}</option>                            
                        {% endfor %}                   
                    </select>
                {% endif %}
            {% if field.name == 'summary' %}        
                <textarea type="text" rows="3" class="form-control" name="{{ field.name }}" id="id_{{ field.name }}">
                    {{ form.fields.summary.initial }}
                </textarea>
            {% endif %}                 
            {% if field.name == 'skillsets' %}        
                <input type="text" placeholder="Separate skills by commas!" class="form-control" name="{{ field.name }}" id="id_{{ field.name }}" value="{{ form.fields.skillsets.initial }}"> 
            {% endif %}                                                     
            </fieldset>
              {% if field.errors %}
            <div style="color:#b94a48">
                {{ field.errors }}
            </div>    
             {% endif %} 
        {% endfor %}
        <input type="hidden" name="username" value="{{user.username}}">        
        <input class="btn btn-default" type="submit" name="providerProfileUpdate" value="Submit" />
        </form>
    </div>
</div>

{% block scripts %}
<script src="https://cdn.rawgit.com/vast-engineering/jquery-popup-overlay/1.7.10/jquery.popupoverlay.js"></script>
{% endblock %}

 <script>
    $(document).ready(function() {
      // Initialize the plugin
        $('#my_popup').popup();

        // List of possible IDs
        languageIds = [1,2,3,4] //To-do: Inject from database here!

        // Hide language 2 and 3 selectors
        $("#language2").hide();       
        $("#language3").hide();
        

        // Keep track of language 1 selector and display lannguage 2 selector
        $("#id_language1").change(function () {

            if ($(this).val() in languageIds) {            
                $("#language2").show();
            }
            if ($(this).val() == 5) {
                $("#language2").hide();
               
            }       
        });

        //var previousLanguage1;
        //$("#id_language1").on('focus', function () {
        //    // Store the current value on focus and on change
        //    previousLanguage1 = $(this).val();
        //}).change(function () {
        //    // Do something with the previous value after the change
        //    if ($(this).val() in languageIds) {
        //        $("#language2 option[value=" + $(this).val() + "]").hide();
        //        $("#language2 option[value=" + previousLanguage1 + "]").show();
        //            $("#language2").show();
        //        }
        //        if ($(this).val() == 5) {
        //            $("#language2").hide();
        //            $("#language2 option[value=" + previousLanguage1 + "]").show();
        //        }  
        //    // Make sure the previous value is updated
        //     previousLanguage1 = $(this).val();
        //});



        // Keep track of language 2 selector and display lannguage 3 selector
        $("#id_language2").change(function () {

            if ($(this).val() == 1 || $(this).val() == 2 || $(this).val() == 3 || $(this).val() == 4) {
                $("#language3").show();
            }
            if ($(this).val() == 5) {
                $("#language3").hide();
            }
        });

        // ######## Hide category functions ########

        // List of possible IDs
        categoryIds = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22] // To-do: Inject from database here!
    
        // Hide categories 2 and 3 selectors
        $("#categories2").hide();
        $("#categories3").hide();


        // Keep track of categories 1 selector and display categories 2 selector
        $("#id_categories1").change(function () {

            if ($(this).val() in categoryIds) {
                $("#categories2").show();
            }
            if ($(this).val() == 23) {
                $("#categories2").hide();
            }
        });

        // Keep track of categories 2 selector and display categories 3 selector
        $("#id_categories2").change(function () {

            if ($(this).val() in categoryIds) {
                $("#categories3").show();
            }
            if ($(this).val() == 23) {
                $("#categories3").hide();
            }
        });


    });

    


    function myFunction() {     
        $('#my_popup').popup('show');      
    }

 

</script>


{% else %}

<h3>Please login!</h3>

{% endif %}

{% endblock %}